name: Update Repository

on: 
  workflow_dispatch:

jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        run: sudo apt-get install -y nodejs && sudo apt-get -y install npm

      - name: Setup Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"

      - name: Install cli
        run: |
          npm i -g @angular/cli
          npm i -g @ionic/cli
      
      - name: Create initialize files
        run: |
          rm -rf init-angular
          rm -rf init-ionic
          ng new init-angular --interactive=false --skip-git=true --skip-install=true --ssr=false --style=scss
          ionic start init-ionic blank --type=angular-standalone --no-deps --no-git

      - name: Commit Repository
        run: |
          git add .
          git diff --staged --exit-code || (git commit -m 'update' && git push)
